In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.combine import SMOTETomek

In [1]:
import pandas as pd
import numpy as np
from imblearn.pipeline import Pipeline
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_validate
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks

In [2]:
df_clean = pd.read_csv('../datasets/cleaned(3).csv')

In [3]:
df_clean.iloc[:,0:6]

,Time,Age_band_of_driver,Sex_of_driver,Vehicle_driver_relation,Driving_experience,Type_of_vehicle
0,Evening,Dewasa,Male,Employee,1-2yr,Private Vehicle
1,Evening,Dewasa,Male,Employee,Above 10yr,Public Transport
2,Evening,Dewasa,Male,Employee,1-2yr,Commercial Vehicle
3,Late Night,Dewasa,Male,Employee,5-10yr,Public Transport
4,Late Night,Dewasa,Male,Employee,2-5yr,NaN
...,...,...,...,...,...,...
12311,Evening,Dewasa,Male,Employee,2-5yr,Commercial Vehicle
12312,Evening,Unknwon,Male,Employee,5-10yr,Private Vehicle
12313,Afternoon,Lansia,Male,Employee,5-10yr,Public Transport
12314,Afternoon,Dewasa,Female,Employee,Above 10yr,Commercial Vehicle
12315,Afternoon,Dewasa,Male,Employee,5-10yr,Other

In [4]:
df_clean.iloc[:,6:12]

,Owner_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type
0,Owner,Urban,Other,Tangent road with flat terrain,No junction,Asphalt roads
1,Owner,Urban,Other,Tangent road with flat terrain,No junction,Asphalt roads
2,Owner,Public,Other,Tangent road with flat terrain,No junction,Asphalt roads
3,Governmental,Urban,Other,Tangent road with mild grade and flat terrain,Y Shape,Earth roads
4,Owner,Urban,Other,Tangent road with flat terrain,Y Shape,Asphalt roads
...,...,...,...,...,...,...
12311,Owner,Rural,Other,Tangent road with flat terrain,No junction,Asphalt roads
12312,Owner,Rural,Other,Escarpments,No junction,Asphalt roads
12313,Owner,Rural,Other,Tangent road with mountainous terrain and,No junction,Asphalt roads
12314,Owner,Urban,Other,Tangent road with mountainous terrain and,No junction,Asphalt roads
12315,Owner,Rural,Other,Tangent road with mountainous terrain and,O Shape,Asphalt roads

In [5]:
df_clean.iloc[:,12:18]

,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties
0,Dry,Daylight,Normal,Stationary Object Collision,2,2
1,Dry,Daylight,Normal,Vehicle Collision,2,2
2,Dry,Daylight,Normal,Stationary Object Collision,2,2
3,Dry,Darkness - lights lit,Normal,Vehicle Collision,2,2
4,Dry,Darkness - lights lit,Normal,Vehicle Collision,2,2
...,...,...,...,...,...,...
12311,Dry,Daylight,Normal,Vehicle Collision,2,1
12312,Dry,Daylight,Normal,Vehicle Collision,2,1
12313,Dry,Daylight,Normal,Vehicle Collision,1,1
12314,Dry,Darkness - lights lit,Normal,Vehicle Collision,2,1
12315,Dry,Darkness - lights lit,Normal,Vehicle Collision,2,1

In [6]:
df_clean.iloc[:,18:22]

,Vehicle_movement,Casualty_severity,Cause_of_accident,Accident_severity
0,Moving forward,3,Moving Backward,Slight Injury
1,Moving forward,3,Reckless Driving,Slight Injury
2,Moving forward,3,Unsafe Lane Change,Serious Injury
3,Moving forward,3,Unsafe Lane Change,Slight Injury
4,Moving forward,3,Reckless Driving,Slight Injury
...,...,...,...,...
12311,Moving forward,3,Distance & Priority Violation,Slight Injury
12312,Other,3,Distance & Priority Violation,Slight Injury
12313,Other,3,Unsafe Lane Change,Serious Injury
12314,Other,3,DUI (Drugs/Alcohol),Slight Injury
12315,Stopping,3,Unsafe Lane Change,Slight Injury

In [ ]:

label_encode_features = ['Age_band_of_driver', 'Driving_experience', 'Casualty_severity', 'Accident_severity']

one_hot_encode_features = [
    'Sex_of_driver', 'Vehicle_driver_relation', 'Type_of_vehicle', 'Owner_of_vehicle',
    'Area_accident_occured', 'Lanes_or_Medians', 'Road_allignment', 'Types_of_Junction',
    'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 'Weather_conditions',
    'Type_of_collision', 'Vehicle_movement', 'Cause_of_accident', 'Time'
]

label_encoder = LabelEncoder()
for feature in label_encode_features:
    df_clean[feature] = label_encoder.fit_transform(df_clean[feature])

df_clean = pd.get_dummies(df_clean, columns=one_hot_encode_features, drop_first=True).astype(int)

print(df_clean.head())

NameError: name 'LabelEncoder' is not defined

In [ ]:
df_clean['Accident_severity']

0        2
1        2
2        1
3        2
4        2
        ..
12311    2
12312    2
12313    1
12314    2
12315    2
Name: Accident_severity, Length: 12316, dtype: int64

In [ ]:
# from imblearn.under_sampling import SMOTENN

# from sklearn.model_selection import train_test_split
# import matplotlib.pyplot as plt
# import seaborn as sns

# X = df.drop(columns=['Accident_severity'], axis=1)
# y = df['Accident_severity']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

# def plot_class_distribution(y_before, y_after, title):
#     fig, axes = plt.subplots(1, 2, figsize=(12, 5))
#     sns.countplot(x=y_before, ax=axes[0])
#     axes[0].set_title("Sebelum Resampling")
    
#     sns.countplot(x=y_after, ax=axes[1])
#     axes[1].set_title("Setelah " + title)

#     plt.show()

# smotetomek = SMOTETomek(random_state=42)
# X_train_smt, y_train_smt = smotetomek.fit_resample(X_train, y_train)

# smotenn = SMOTENN(random_state=42)
# X_train_smn, y_train_smn = smotenn.fit_resample(X_train, y_train)

# plot_class_distribution(y_train, y_train_smt, "SMOTETomek")
# plot_class_distribution(y_train, y_train_smn, "SMOTENN")

ImportError: cannot import name 'SMOTENN' from 'imblearn.under_sampling' (/home/ahmadnafim/anaconda3/envs/bcc_intern/lib/python3.9/site-packages/imblearn/under_sampling/__init__.py)

In [8]:
X = df_clean.drop(columns='Accident_severity', axis=0)
y = df_clean['Accident_severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X, y = make_classification(n_classes=2, class_sep=2,
weights=[0.1, 0.9], n_informative=3, n_redundant=1, flip_y=0,
n_features=20, n_clusters_per_class=1, n_samples=1000, random_state=10)
print('Original dataset shape %s' % Counter(y))
smt = SMOTETomek(random_state=42)
X_res, y_res = smt.fit_resample(X, y)
print('Resampled dataset shape %s' % Counter(y_res))

NameError: name 'train_test_split' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTETomek
from sklearn.datasets import make_classification
from collections import Counter

X = df_clean.drop(columns=['Accident_severity']) 
y = df_clean['Accident_severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print('Original dataset shape:', Counter(y_train))

smt = SMOTETomek(random_state=42)
X_train_res, y_train_res = smt.fit_resample(X_train, y_train)
print('Resampled dataset shape:', Counter(y_train_res))

Original dataset shape: Counter({2: 7013, 1: 1137, 0: 101})
Resampled dataset shape: Counter({0: 7005, 1: 6959, 2: 6953})

In [ ]:
X, y = make_classification(n_classes=2, class_sep=2, weights=[0.1, 0.9], 
                           n_informative=3, n_redundant=1, flip_y=0, 
                           n_features=20, n_clusters_per_class=1, 
                           n_samples=1000, random_state=10)

print('Original dataset shape:', Counter(y))

# Oversampling dengan SMOTETomek
smt = SMOTETomek(random_state=42)
X_res, y_res = smt.fit_resample(X, y)
print('Resampled dataset shape:', Counter(y_res))

Original dataset shape: Counter({np.int64(1): 900, np.int64(0): 100})
Resampled dataset shape: Counter({np.int64(0): 900, np.int64(1): 900})